language: php
php:
  - 5.4
  - 5.5
  - 5.6
addons:
  firefox: "41.0"
before_script:
 - mysql < app/database/helpdesk.sql -uroot
 - wget http://getcomposer.org/composer.phar
 - php composer.phar install
 - "sh -e /etc/init.d/xvfb start"
 - "export DISPLAY=:99.0"
 - "wget http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar"
 - "java -jar selenium-server-standalone-2.45.0.jar > /dev/null &"
 - sleep 5
 - php -S 127.0.0.1:8090 app/.htrouter.php &
 - sleep 5
script: (cd tests; phpunit --configuration PHPunit.xml --debug)